services:
  backend-crud-service:
    build: #build latest image of spring boot
      #when docker compose change file location, we need to write path of this in context instead of .
      context: .
      args:
        - DOCKER_BUILDKIT=1 #makes faster bundling
    container_name: backend-crud-service
    ports:
      - 8080:8080
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/seasonal_jobs_db
    #   SPRING_DATASOURCE_USERNAME: postgres
    #   SPRING_DATASOURCE_PASSWORD: postgres
    environment:
      # SPRING_DATASOURCE_URL: ${JDBC_DATABASE_URL}
      # SPRING_DATASOURCE_USERNAME: ${JDBC_DATABASE_USERNAME}
      # SPRING_DATASOURCE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://c2ath2egdsh9dm.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d5183gpg7pokjv
      - SPRING_DATASOURCE_USERNAME=u8c6vf5b77entb
      - SPRING_DATASOURCE_PASSWORD=pbc4e019489c5dcc3be5e501aed4fba46b7727ad545eddf4f93a921fce710c9fa
  
  # database:
  #   container_name: database
  #   image: postgres:17.6-bookworm
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: seasonal_jobs_db
      #DB name
volumes:
  postgres_data:
